<?php goodresto_enovathemes_global_variables(); ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-facebook']): ?><a class="et-icon-facebook" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-facebook']); ?>" title="facebook" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-twitter']): ?><a class="et-icon-twitter" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-twitter']); ?>" title="twitter" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-googleplus']): ?><a class="et-icon-google" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-googleplus']); ?>" title="google plus" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-vk']): ?><a class="et-icon-vk" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-vk']); ?>" title="vk" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-youtube']): ?><a class="et-icon-youtube" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-youtube']); ?>" title="youtube" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-vimeo']): ?><a class="et-icon-vimeo" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-vimeo']); ?>" title="vimeo" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-linkedin']): ?><a class="et-icon-linkedin" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-linkedin']); ?>" title="linkedin" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-pinterest']): ?><a class="et-icon-pinterest" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-pinterest']); ?>" title="pinterest" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-instagram']): ?><a class="et-icon-instagram" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-instagram']); ?>" title="instagram" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-apple']): ?><a class="et-icon-apple" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-apple']); ?>" title="apple" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-dribbble']): ?><a class="et-icon-dribbble" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-dribbble']); ?>" title="dribbble" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-android']): ?><a class="et-icon-android" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-android']); ?>" title="android" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-behance']): ?><a class="et-icon-behance" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-behance']); ?>" title="behance" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-tripadvisor']): ?><a class="et-icon-tripadvisor" href="<?php echo esc_url($GLOBALS['goodresto_enovathemes']['social-tripadvisor']); ?>" title="tripadvisor" target="_blank" ></a><?php endif; ?>
<?php if($GLOBALS['goodresto_enovathemes']['social-email']): ?><a class="et-icon-email" href="mailto:<?php echo esc_attr($GLOBALS['goodresto_enovathemes']['social-email']); ?>" title="email" target="_blank" ></a><?php endif; ?>
